  # YAML file for testing different server types
  -
    servertype: Go
    url: http://goserver.localdomain:8153/go
    username: ci
    password: secret
    pipelines:
      -
        name: "Bravo"

  -
    servertype: CruiseControl
    url: http://cruisecontrol.localdomain:8080
    username: ci
    password: secret
    pipelines: